FROM ruby:3.3.6-slim-bullseye
RUN apt-get update -qq && apt-get install -y \
  build-essential \
  sqlite3 \
  libsqlite3-dev \
  git
WORKDIR /usr/src/app
ENV BUNDLE_PATH=/usr/src/app/vendor/bundle
RUN echo "source 'https://rubygems.org'\ngem 'rails', '~> 8.0.0'\ngem 'sqlite3'" > Gemfile && \
    touch Gemfile.lock
COPY setup.sh /usr/src/app/setup.sh
RUN chmod +x /usr/src/app/setup.sh
RUN bundle install
EXPOSE 3000
ENTRYPOINT ["sh", "/usr/src/app/setup.sh"]
